# Outlier Detection - OneClassSVM

Unsupervised Outlier Detection.

Estimate the support of a high-dimensional distribution.

The implementation is based on libsvm.

User Guide: https://scikit-learn.org/stable/modules/outlier_detection.html#outlier-detection

## Dependencies

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Read data

In [4]:
df = pd.read_csv('Nov2Temp.csv')
df.drop([72, 79], inplace = True)
df

     high  low
0      58   25
1      26   11
2      53   24
3      60   37
4      67   42
..    ...  ...
115    99   33
116    99   27
117    18   38
118    15   51
119    30   49

[118 rows x 2 columns]

In [5]:
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler

X = StandardScaler().fit_transform(df)
clf = OneClassSVM(kernel = 'linear').fit(X)
pred = clf.predict(X)
df[pred == -1]

     high  low
43     76   54
111    48   99
112    43   99
113    64   99
118    15   51
119    30   49

One Class SVM by Di Wu is licensed under [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). It adapts the tutorial of Outlier Detection of scikit-learn (https://scikit-learn.org/stable/modules/outlier_detection.html#outlier-detection).

2007 - 2023, scikit-learn developers (BSD License).
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
Disclaimer: THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.